### PR TITLE
Add Silverblue with description to metadata.json

### PR DESCRIPTION
**Pull request by vojteskas**

### CODE REVIEW

**Comment by vojteskas** [comment]
Text metadata is included in this PR, but there is no Silverblue icon yet. I don't really know where to get it and how to include.

**Comment by grulja** [comment]
Can you please open this against master? You can get the icon from https://silverblue.fedoraproject.org/public/silverblue-logo.svg.

**Comment by grulja** [comment]
> Can you please open this against master? You can get the icon from https://silverblue.fedoraproject.org/public/silverblue-logo.svg.

Sorry, you obviously can't, because the logo needs to be in a circle to follow design of the other icons. Then we will need to ask the design team for help.

**Comment by vojteskas** [comment]
Yeah, sorry, will open it against master!

**Pull request closed without merging**
