### PR TITLE
Create winget.yml

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` and `workflow` scopes as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @FedoraQt.

* Resolves https://github.com/FedoraQt/MediaWriter/issues/551

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
cc @grulja

**Comment by grulja** [comment]
> cc @grulja

I'm aware. I was planning to look into this. 

> This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
> 
> Before merging this:
> 
> 1. Please add a GitHub token with `public_repo` and `workflow` scopes as a repository secret and rename the secret name in the workflow.

I'm not sure what token I should add.

**Comment by vedantmgoyal2009** [comment]
- Go to https://github.com/settings/tokens/new
- Enter a token name (it can be anything, you want)
- Select `public_repo` and `workflow` in the permissions section
- Click "generate token" and copy the token to the clipboard.

After this, you've to add it as a repository secret. For this:
- Visit https://github.com/FedoraQt/MediaWriter/settings/secrets/actions/new
- Enter the information as shown in the below screenshot: 
image

Finally, it would look like this: 
image

**Comment by grulja** [comment]
It looks when I check `workflow` it automatically checks all `repo` access, like `repo:status`, `repo_deployment` etc. so it's not possible to only check `public_repo` in this combination. I will read more documentation about what this all means.

**Comment by vedantmgoyal2009** [comment]
Only `public_repo` will work. `workflow` is only required in some special cases, like: https://github.com/sandboxie-plus/Sandboxie/runs/7931748039?check_suite_focus=true#step:2:173.

**Pull request merged**
