### PR TITLE
Use portal file dialog when possible to avoid native dialog issues

### PR DESCRIPTION
**Pull request by grulja**
There is a bug in QML file dialog [1] causing file dialog freeze in some cases. This should workaround this issue.

Fixes: https://github.com/FedoraQt/MediaWriter/issues/277 and https://github.com/FedoraQt/MediaWriter/issues/339
RH Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1977472

[1] - https://bugreports.qt.io/browse/QTBUG-59184

### CODE REVIEW

**Comment by grulja** [comment]
Can anyone try if this fixes the issue for him? @coz @mikunimaru?

**Comment by mikunimaru** [comment]
Sorry for the beginner's question, how can I convert this commit to rpm?

**Comment by grulja** [comment]
> Sorry for the beginner's question, how can I convert this commit to rpm?

You can try this one https://koji.fedoraproject.org/koji/taskinfo?taskID=71841843. Try to download it as soon as possible as the build will be gone soon.

**Comment by mikunimaru** [comment]
I tested it immediately.
The selection screen no longer freezes even without the QGnomePlatform.

**Comment by grulja** [comment]
> I tested it immediately.
> The selection screen no longer freezes even without the QGnomePlatform.

Thank you for testing it.

**Pull request merged**
