### PR TITLE
Add Fedora KDE Mobile spin to the list

### LINKED ISSUE #734: Using media writer installs mobile version of KDE instead of desktop
On version 5.1.2 of media writer with the following system information:
image

Selecting 'Download automatically', then Spins with 'Fedora KDE Plasma Desktop' selected and installing Fedora 41 Beta on to a USB drive caused it to write Fedora KDEM and not KDE (it still said it was writing KDE plasma desktop while writing)
image
Booting into the USB also shows KDE mobile.

### PR DESCRIPTION
**Pull request by grulja**
Fixes #734

### CODE REVIEW

**Review by gastoner — APPROVED** [review]
LGTM

**Comment by AdamWill** [comment]
I don't understand the comment "// KDE Mobile spin uses same subvariant as KDE Desktop". It doesn't. It uses KDE_Mobile - https://pagure.io/pungi-fedora/blob/main/f/fedora.conf#_491 . It has done since it was added in https://pagure.io/pungi-fedora/c/6bfb1a6484fc6e0e6b71c1d70067cad503579ba1 .

**Comment by grulja** [comment]
From `releases.json`:
```
  {
    "version": "41 Beta",
    "arch": "x86_64",
    "link": "https://download.fedoraproject.org/pub/fedora/linux/releases/test/41_Beta/Spins/x86_64/iso/Fedora-KDE-Mobile-Live-41_Beta-1.2.x86_64.iso",
    "variant": "Spins",
    "subvariant": "KDE"
  },
```

**Comment by grulja** [comment]
Also see https://pagure.io/releng/issue/12369.

**Comment by AdamWill** [comment]
If you search https://dl.fedoraproject.org/pub/alt/stage/41_Beta-1.2/metadata/images.json for "Mobile", every image you'll find has the subvariant 'KDE_Mobile'. releases.json is created by something that's part of websites code, I suspect maybe it has a problem with subvariants that are substrings of other subvariants.

I do wonder if your code is safe here, too - you have a check `if (r->name().toLower().contains(release) || r->subvariant().toLower().contains(release))`, I wonder if maybe the subvariant case there ought to be an equality check, not a contains check.

**Pull request merged**
