### PR TITLE
Add the Fedora IoT edition

### PR DESCRIPTION
**Pull request by D4N**
cc @nullr0ute

### CODE REVIEW

**Comment by grulja** [comment]
@allanday,  @MartinBriza: what do you think? Do we want to hide the "Custom image" option?

This is how it was before: 
fmw-old

This is how it looks now:
fmw-new

**Comment by dreua** [comment]
> Do we want to hide the "Custom image" option?

As a user, I'd vote against hiding the "Custom image" option. It is an important function of FMW in my opinion and probably more often used than Fedora IoT.

**Comment by grulja** [comment]
There is option 3) and that is show all of them, because there is still plenty of space.

**Comment by D4N** [comment]
It was not really my intention to hide the "Custom image" option, I can try to display all 3 editions + "Custom image".

**Comment by D4N** [comment]
@grulja Can we move this forward? If there is no interest in having the IoT edition, then I can close this PR too.

**Comment by grulja** [comment]
I'm not against it, I was just waiting for you to update the PR to not hide the "Custom image" option.

**Comment by D4N** [comment]
> I'm not against it, I was just waiting for you to update the PR to not hide the "Custom image" option.

Should be done now, but please double check it, because I am really not familiar with Qt and QML and was searching for the correct places to change for the past hour.

**Comment by grulja** [comment]
fmw

Hmm, this doesn't look good. I wonder what to do about it, because if we move the view to the center (vertically), then there is not enough space for the notification which popups and asks users about device restoration. Maybe we can make the window bigger by default?

@allanday what do you think?

**Comment by MartinBriza** [comment]
FMW did actually have 3 different fedora releases on the title screen
initially when it was released (Cloud was in the UI back then, before being
removed for the lack of an ISO image). The list was centered on the main
screen and the notification fit, I think. If it doesn't, the window could
be just slightly larger, it's not very big now.

**Comment by grulja** [comment]
@D4N can you update the PR making the main window bigger and move the list with Fedora variants to the center (vertically)?

**Comment by grulja** [comment]
See https://github.com/FedoraQt/MediaWriter/pull/433. The only missing part is to update releases.json with IoT downloads as they don't seem to be on the official list.

**Pull request closed without merging**
